spring:
  application:
    name: java-seed
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${configuration.kafka.schema-registry-url}
  cloud:
    function:
      definition: userOrderTopology;userOrderListener;
    stream:
      kafka:
        streams:
          binder:
            application-id: "${configuration.kafka-prefix}.user_order_topology"
            brokers: "${spring.kafka.bootstrap-servers}"
            configuration:
              specific.avro.reader: true
              default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              schema.registry.url: ${configuration.kafka.schema-registry-url}
      bindings:
        userOrderTopology-in-0:
          destination: "${configuration.kafka.topics.user}"
        userOrderTopology-in-1:
          destination: "${configuration.kafka.topics.order}"
        userOrderTopology-out-0:
          destination: "${configuration.kafka.topics.user_order}"
        userOrderListener-in-0:
          destination: "${configuration.kafka.topics.user_order}"
          group: "${configuration.kafka.application-prefix}.user-order-listener"

configuration:
  kafka:
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    application-prefix: java-seed
    topics:
      user: user_topic
      order: order_topic
      user_order: user_order_topic
