openapi: 3.0.3
info:
  title: ZPayment
  version: 1.0.0
  description: Project that emulate payment processing with fraud check
tags:
  - name: Payments
    description: Payments operations

paths:
  /v1/payments:
    post:
      tags:
        - Payments
      summary: Process a payment
      operationId: processPayment
      parameters:
        - name: Idempotency-Key
          in: header
          description: Unique key to ensure idempotency of the request.
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequest'
      responses:
        '201':
          description: Payment processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '200':
          description: Existing payment returned due to idempotency
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '422':
          description: Payment rejected due to invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /v1/payments/{id}:
    get:
      tags:
        - Payments
      summary: Retrieve payment details
      operationId: getPaymentById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Payment details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '404':
          description: Payment not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    PaymentRequest:
      type: object
      required:
        - account_id
        - beneficiary
        - currency
        - amount
      properties:
        account_id:
          type: string
          format: uuid
        beneficiary:
          type: string
          format: uuid
        currency:
          $ref: '#/components/schemas/CurrencyEnum'
        amount:
          type: integer
          minimum: 1


    PaymentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        state:
          $ref: '#/components/schemas/PaymentStateEnum'

    CurrencyEnum:
      type: string
      enum:
        - GBP
        - USD
        - EUR
        - BRL

    PaymentStateEnum:
      type: string
      enum:
        - PENDING
        - UNDER_REVIEW
        - APPROVED
        - REJECTED

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
