server:
  port: 8080
  shutdown: GRACEFUL

spring:
  application:
    name: zpayment
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/vpayment}
    username: ${DATABASE_USERNAME:vpayment}
    password: ${DATABASE_PASSWORD:vpayment}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
    producer:
      transaction-id-prefix: ktx-
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: ${configuration.kafka.schema-registry-url}
  cloud:
    function:
      definition: paymentFraudTopologyV1;paymentProcessResultListenerV1;
    stream:
      kafka:
        streams:
          binder:
            application-id: "${configuration.kafka.application-prefix}.payment_process_topology"
            brokers: ${spring.kafka.bootstrap-servers}
            configuration:
              commit.interval.ms: 0
              specific.avro.reader: true
              default.key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
              schema.registry.url: ${configuration.kafka.schema-registry-url}
              state.dir: ${configuration.kafka.state-dir}
        bindings:
          paymentProcessResultListenerV1-in-0:
            consumer:
              configuration:
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                specific.avro.reader: true
                schema.registry.url: ${configuration.kafka.schema-registry-url}
      bindings:
        paymentFraudTopologyV1-in-0:
          destination: "${configuration.kafka.topics.payment-submission}"
        paymentFraudTopologyV1-in-1:
          destination: "${configuration.kafka.topics.fraud-result}"
        paymentFraudTopologyV1-out-0:
          destination: "${configuration.kafka.topics.payment-process-result}"
        paymentProcessResultListenerV1-in-0:
          destination: "${configuration.kafka.topics.payment-process-result}"
          group: "${configuration.kafka.application-prefix}.payment-result-listener"

configuration:
  kafka:
    state-dir: /tmp/kafka-streams/payment
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    application-prefix: payment
    topics:
      payment-submission: payment_submission
      fraud-result: fraud_gateway_result
      payment-process-result: payment_process_result
